services:
  proxy:
    image: envoyproxy/envoy:dev
    volumes:
    - ${PWD}/docker/envoy.yaml:/etc/envoy.yaml 
    - ${PWD}/target/wasm32-unknown-unknown/release/envoy_filter_customer_lookup.wasm:/lib/envoy_filter_customer_lookup.wasm
    depends_on:
    - web_service
    ports:
    - "8000:8000"
    command: /usr/local/bin/envoy -c /etc/envoy.yaml --service-cluster proxy -l info

  web_service:
    image: ealen/echo-server:0.7.0
    ports:
      - 80:80